### ISSUE TITLE
For level API

### ISSUE THREAD

**Issue by wrewolf** [PocketMine/Documentation#3]
How to get block and change bloc

//change
$this->api->level->getDefault()->setBlock(new Vector3(90,70,126), new StoneBlock() );
//get
$block=$this->api->level->getDefault()->getBlock(new Position(90,70,126,$this->api->level->getDefault()))->getName());

**Comment by mengliang818** [comment]
do you know how to make Chest protected by the player who paste down?

**Comment by wrewolf** [comment]
You have give code from ChestShop
now you have create shop and breack sign, but chest is privated

**Comment by mengliang818** [comment]
really? but din't have a plugin only for Chest Protection?

**Comment by mengliang818** [comment]
Do you know the code for SimpleAuth when login player wont get damage...after login player will get damage

**Comment by wrewolf** [comment]
https://gist.github.com/wrewolf/5821311
but i not test this code, this mental adaptation code ChestSop to CestProtect

**Comment by wrewolf** [comment]
for not get damage you need handle
$this->api->addHandler("player.interact", array($this, "eventHandler"));
and return false whis damage getted from unregister user,
a not have a time to write plugin, but another peoples maybe write this

**Comment by mengliang818** [comment]
okay =D thanks

**Comment by mengliang818** [comment]
i test your ChestProtect

**Comment by mengliang818** [comment]
11:25:34 [ERROR] A level 4096 error happened: "Argument 2 passed to PocketMinecraftServer::addHandler() must be callable, array given, called in /root/three/src/API/ServerAPI.php on line 312 and defined" in "/root/three/src/PocketMinecraftServer.php" at line 265

it has this error...when put in the ChestProtect.php

**Comment by wrewolf** [comment]
Oh, i find this mistake and update gist, you can try again

**Comment by mengliang818** [comment]
updated?

**Comment by mengliang818** [comment]
great...thanks

**Comment by wrewolf** [comment]
Yes, gist is a simple git repos with web access and online editing

**Comment by mengliang818** [comment]
the file with ChestProtect is not .php ...should i just type .php behind the file?

**Comment by wrewolf** [comment]
download 
https://gist.github.com/wrewolf/5821311/raw/18033b7dc1b31435e258c0c2a32f7b1087a90de7/ChestProtect
and save as 
ChestProtect.php

**Comment by wrewolf** [comment]
fix file extention for easy access

**Comment by mengliang818** [comment]
ok
 Thanks so much

**Comment by mengliang818** [comment]
sorry for disturb agian =o=
Parse error: syntax error, unexpected '&' in /root/three/src/API/PluginAPI.php(93) : eval()'d code on line 24
11:40:00 [ERROR] Failed loading plugin: evaluation error

**Comment by mengliang818** [comment]
but its okay...i copy all the codes to new .php files =D hope its work

**Comment by mengliang818** [comment]
hmmm seems like not working @.@

**Comment by mengliang818** [comment]
still able to open from others

**Comment by wrewolf** [comment]
ok, i fix it

**Comment by iksaku** [comment]
@wrewolf the function for block change will also update other blocks nearby?

**Comment by wrewolf** [comment]
@iksaku 
public function setBlock(Vector3 $pos, Block $block, $update = true, $tiles = false, $direct = false)

**Comment by iksaku** [comment]
@wrewolf Thank You! Another one: is it possible to change blocks between a specific coords? Like: 1, 1, 1 & 5, 5, 5

**Comment by wrewolf** [comment]
@iksaku no.

**Comment by iksaku** [comment]
@wrewolf other one, is possible to check if a (ex.) param is equal to a username of an online player? Like: 
`if($params[0] != $username) {
    return "not a valid username";
  }`
